### ISSUE TITLE
Add reference documentation to Contributing file

### ISSUE THREAD

**Issue by ODXT** [devRant-Community/Community-Programming-Book#13]
Add documentation for writers to follow when creating their chapter.

**Comment by ODXT** [comment]
I believe the latest merge took care of this. But we should review.

**Comment by Skayo** [comment]
In this documentation, there should be a style guide according to the configuration in .mdlintrc

**Comment by ODXT** [comment]
Also, as mentioned in the discord server, we should standarize the tone and other things. Like first or third person.

**Comment by FilipeRamalho** [comment]
How should we decide on these Questions ? We could wait for the first chapters and then standardize or standardize now and adapt in future.

**Comment by gadilashashank** [comment]
Some issues need to be standardized now like the usage of "you" for instance. Because later changing some aspects might be too difficult.

**Comment by ODXT** [comment]
I agree with @gadilashashank. But I don't know how to go about choosing. I propose we do some research on the subject and come back with an option. For example, I could go to Wikipedia get some psychology reference that using you is good. This way we don't waste time debating. We just get previous arguments to defend our point. 

I'm all ears for other suggestions, but this is my proposal.

**Comment by gadilashashank** [comment]
@ODXT @Skayo @FilipeRamalho Please review my re-written contributing guide in #30

**Comment by lucaspar** [comment]
Closing issue as #30 was merged.
