### ISSUE TITLE
Catchy Name ?

### ISSUE THREAD

**Issue by ODXT** [devRant-Community/Community-Programming-Book#14]
Ticket will be closed this Saturday (20180602). Please leave your suggestions and vote before then. 

**Edit**
Winner: A Ginormous Guide for the Myriad of Languages - A devRant collab

**Comment by FilipeRamalho** [comment]
A story of code

**Comment by Electrux** [comment]
A Ginormous Guide for the Myriad ( of ) Languages

**Comment by ODXT** [comment]
Programming Languages - a devRant guide 

(not really a guide tho)

**Comment by FilipeRamalho** [comment]
Programmer's Encyclopedia. Maybe we could leave the frame of languages and also talk about programming tools. 🤷‍♂️

**Comment by Charon92** [comment]
From C to R - The (Almost) Programmers Guide.

**Comment by FilipeRamalho** [comment]
@Charon92 This will become a Problem, you could also say Binary to Java or Assembly to C++, the book is for every language and not just the ones between C and R.

**Comment by ODXT** [comment]
A footnote on the history of Programming (language)

Meh

**Comment by ODXT** [comment]
Buzzword - The Book

**Comment by Charon92** [comment]
@FilipeRamalho I'm guessing my attempt at a joke was too subtle.

I meant it like "A - Z" but with just language names seeming like we've missed a few.

**Comment by FilipeRamalho** [comment]
@Charon92 I guessed you could have meant that, but it is really too subtle.

**Comment by FilipeRamalho** [comment]
Please endorse the titles you like with an 👍 and the one you love most with ❤️ .

**Comment by Charon92** [comment]
"The Painfully Thorough Guide to Everything."

**Comment by Charon92** [comment]
"The Fu***ng Manual"

**Comment by FilipeRamalho** [comment]
@Charon92 🤔 Not sure if I should add that to the list.

**Comment by Charon92** [comment]
@FilipeRamalho but then when someone says "RTFM" you literally could. It's free advertising.

**Comment by FilipeRamalho** [comment]
@Charon92 That's a really good argument. I'll add it

**Comment by ODXT** [comment]
@Charon92 maybe add an * to "Everything". Like this "Everything*".

That way it's like everything, everything related to developing.

**Comment by lucaspar** [comment]
"The Programmer's Guide to the Galaxy" :laughing: 
but then there's this already http://www.programmersguidetothegalaxy.com/

**Comment by lucaspar** [comment]
@Charon92 then we can upgrade to
From A+ to Z shell - The ~(Almost)~ Complete Programmer's Guide.

**Comment by gadilashashank** [comment]
I'll just leave this here: 
After the name is decided we need to possibly change the gitbook subdomain to <new name>.gitbook.io/book

**Comment by FilipeRamalho** [comment]
@gadilashashank depends on the name size.

**Comment by RootPixl** [comment]
Developer's  Encyclopedia is a good name
Also, as a kinda motto for it that could be 'From Community for Community' or something like that

**Comment by FilipeRamalho** [comment]
@ODXT when should we close it ? Midnight UTC ? That would be in 4 Hours.

**Comment by FilipeRamalho** [comment]
I guess that by now it's officially closed.
We have a tie between "A Ginormous Guide for the Myriad ( of ) Languages" and "Developer's Encyclopedia"

**Comment by RootPixl** [comment]
Maybe we could make a little pool, leave it *somewhere in the Internet* and community will decide?

**Comment by RootPixl** [comment]
Maybe we could make a little pool, leave it *somewhere in the Internet* and community will decide?

**Comment by FilipeRamalho** [comment]
A pool ?

**Comment by gadilashashank** [comment]
My opinion
"A Ginormous..." sounds better, interesting and more unique..

**Comment by FilipeRamalho** [comment]
@gadilashashank Yesterday there weren't any votes, so I guess that won't change much.

**Comment by RootPixl** [comment]
* poll

**Comment by FilipeRamalho** [comment]
@RootPixl That's what we did here

**Comment by RootPixl** [comment]
I mean, poll using Google forms or Strawpoll or anything like that and sending links to our friends or someone to get more votes than just here

**Comment by Skayo** [comment]
> Programmer's wet dream
> Programming Languages - How they fuck your mind
> Programming Languages - How they differ
> Holy codes
> Programming Shit

As we are coming from the devRant Community, I think we need a fitting title

**Comment by Skayo** [comment]
@devRant-Squad/community-programming-book Please vote here:
https://github.com/devRant-Squad/Community-Programming-Book/blob/master/README.md

**Comment by ODXT** [comment]
Hey guys sorry about the delay. Still dealing with some things on my end. I'll be taking the most popular options into a list to make a final vote. I think @RootPixl's idea for a poll is good. Will probably update tonight.

**Comment by Skayo** [comment]
@ODXT uhm. Already made a poll? README?

**Comment by ODXT** [comment]
We'll shit, you work fast. Nevermind then.

**Comment by 7root** [comment]
Vim like a boss.

**Comment by ODXT** [comment]
I think the title was been mostly settled in the poll. I'll be closing it this weekend, probably Saturday night. So please cast your last minute votes in the next few days.

**Comment by ODXT** [comment]
So... I meant to close this, with the winner, past weekend. But we're at a tie, and it didn't break over the weekend. 

Again...

Let's go over this in the Discord server, and try to close this today.
