### ISSUE TITLE
Add chapters for weird languages.

### ISSUE THREAD

**Issue by FilipeRamalho** [devRant-Community/Community-Programming-Book#15]
For example we could add Emojicode, It's a rather unknow language, but the book needs some weirdness and fun. 😸 

- [ ] Emojicode
- [ ] Malboge
- [ ] DNA
- [ ] Shakespeare
- [ ] Brainfuck

**Comment by RootPixl** [comment]
So if there would be Emojicode language, there also should be most weird programming languages like Malbolge, DNA, Chicken, Sheakspeare, you know what I mean :wink:

**Comment by c3ypt1c** [comment]
What about the classic Mindfuck language? I've checked the book so far on GitBook and it doesn't seem to be there much yet.

**Comment by FilipeRamalho** [comment]
@c3ypt1c I added it

**Comment by KrzysztofSzewczyk** [comment]
I'm currently hacking on the more popular esoteric languages, so I think this issue can be safetly closed.
