### ISSUE TITLE
Publishing the book

### ISSUE THREAD

**Issue by Skayo** [devRant-Community/Community-Programming-Book#27]
We need to find a way to publish the book once it is finished.

Ways to do it:
- Just use GitBook < Nothing (Still waiting for their API)
- https://www.softcover.io/< Generate PDF, E-Pub, etc. - also allows selling the book - professional
- https://penflip.com/ < PDF, E-Pub export - does not integrate with Github
- https://github.com/bryanbraun/franklin < Static book website - complicated to switch to
- Make own script with gimli or similar

**Comment by FilipeRamalho** [comment]
I'm seeing there is a lot of will of Progress, but again we currently have on language *barely* made and two other waiting with their begin and a ton of more not even written ones.
Slow down and only talk about it when we have a considerate number.

**Comment by Skayo** [comment]
Okay

**Comment by RootPixl** [comment]
Found this: https://www.springeropen.com/books
We shall be interested in this in near future.

**Comment by Unrooted** [comment]
# Writeup
I think, that the ebook version shall become free as it is already on GitBook.
Printing the book is a good idea, here are some of our options:
* [**StreetLib**](https://www.streetlib.com/print) - selling books on Amazon, including UK, US, DE and few others. They also have a nice revenue calculator. 
* [**MTP**](https://www.mtp.agency) - another nice printing service, I've sent them an email to ask about the pricing and selling the book. 
* [**BLURB**](http://www.blurb.com) - just a printing service.
* [**Sweek**](https://selfpublish.sweek.com/publish-book/) - service including printing and selling the book, even in the bookstores.
That's probably it, they are the best from what I've seen and heard. If you know other ways of publishing - cool, tell about them. 
Also, about the publishing, don't get me wrong guys, I think giving at least 10% of the money made on each book to the charity would be nice. 
What do you think?

**Comment by Unrooted** [comment]
# Update

It's been a while now. I've been contacting both MTP and StreetLib. 

StreetLib's printing service for now is limited to only Italian-authors. So, well, we can't go with them.
But, MTP is an international agency. They want 250GBP before releasing and another 250GBP right before printing first books (they need to ship it to some bookshops, you know). 
Whole team agreed on using MTP service. We've started raising money, and we will promote this thing on devRant and Twitter (to raise more money) this fall. 

If you'll find better offer than that from MTP, tell about it. 

I think we can close this issue for now.

**Comment by Unrooted** [comment]
# Update
As a team, during the latest discussion, we have decided on a strategy...

Content on the site will remain free and the project will still be open-source.
But if someone wants to support authors, he/she can buy pdf export or printed version of the book. 
We do also thought about making the book (as a pdf export) free for students.
We have had discussed, 50% of the profit will go to the charity/supporting open-source projects.
@gadilashashank said something about selling the book in volumes, but not many publishers even offer that, so well, that's the only problem here, but it would be way easier to update just specified volumes, not a whole book. We're currently looking for a publisher that offers that or we'll stay with MTP or StreetLib.
There's also an option that we'd go with Blurb, we can sell the book in the volumes even as a magazine, but then we can't sell it through our own website (same with MTP and StreetLib) and selling it through our own website was also suggested by @gadilashashank. I do like the idea. I also do like the idea to sell the book on devRant's store if the devRant's maintainers would agree.
